name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  # The path inside the Ruby repo's public folder
  APP_PATH: /ruby-bfsi-demo-test/demos/usecases
  # The path to your React project in THIS repo
  PROJECT_DIR: use-case-demos/static-tpp-application

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./use-case-demos/static-tpp-application

    steps:
      - name: Checkout React Repo
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: >-
            {"cwd":"use-case-demos/static-tpp-application"}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build vite React app
        run: pnpm vite build --base=${{ env.APP_PATH }}/

      - name: Inject asset base path
        run: |
          sed -i "s|__ASSET_BASE__|${{ env.APP_PATH }}|g" public/configurations/config.json

      - name: Clone Ruby repo
        working-directory: ./
        run: |
          git clone https://x-access-token:${{ secrets.RUBY_REPO_TOKEN }}@github.com/${{ secrets.RUBY_REPO_OWNER }}/${{ secrets.RUBY_REPO_NAME }}.git ruby-repo

      - name: Copy build output
        working-directory: ./
        run: |
            # Target the demos/usecases folder directly (where your React app should live)
            rm -rf ruby-repo/demos/usecases/* mkdir -p ruby-repo/demos/usecases
            cp -r ${{ env.PROJECT_DIR }}/dist/* ruby-repo/demos/usecases/

      - name: Commit and push
        working-directory: ./ruby-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: deploy React build to ${{ env.APP_PATH }}" || echo "No changes"
          git push
